version: '3.7'
services:
  neo4j:
    image: neo4j:4.4.2
    restart: always
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/letmein
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
  import:
    build:
      context: ./import
    hostname: import
    restart: always
    container_name: import
    links:
        - neo4j
    depends_on:
      - neo4j
  neodash:
    image: nielsdejong/neodash
    restart: always
    hostname: neodash
    container_name: neodash
    network_mode: bridge
    ports:
      - 80:5005
    depends_on:
      - neo4j
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass test --loglevel warning
